# Site settings
title: ARS-MATRIX
description: 'Brevity is the soul of wisdom'
url: ''
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Danyang (Arthur R) Song'
  email: arthur.r.song@gmail.com
  twitter_username: arthur_r_song
  github_username: GreysTone
  linkedin_username: danyang-arthur-song-14595291

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

# Plugins
plugins_dir:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-admin

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'run_local.sh']
