# Site settings
title: ARS Matrix
description: 'Brevity is the soul of wisdom'
url: ""
baseurl: ""
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Danyang (Arthur) Song'
  email: arthur.r.song@gmail.com
#  twitter_username: 
#  facebook_username: 
#  github_username:  
#  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
